### ISSUE TITLE
How are the webcam cameras and lidar,imu synchronized using ros?

### ISSUE THREAD

**Issue by poornimajd** [mikkelkh/FieldSAFE#5]
Thanks for the open-source.
I just found this from your paper-

_remaining   sensors   were   synchronized   in software using a best effort approach in ROS_

under the topic synchronization in section 2-sensor setup.
I wanted to know how exactly the usb webcam,lidar and imu can be synchronized using ROS.
Also,what was the synchronization error you obtained using ROS.
Any suggestion is greatly appreciated.
Thankyou

**Comment by mikkelkh** [comment]
Hi there

The only sensors that were properly synchronized were the lidar, stereo camera and thermal camera. These were synced in hardware using trigger signals. The remaining sensors (webcam, IMU) were interfaced and synchronized using a best-effort approach in ROS. That is, all sensor messages were timestamped at their arrival by the ROS system time. The best-effort message delivery, however, did not guarantee specific delivery times, and the actual time delays therefore depended on internal sensor processing times, transmission times, network traffic load, software drivers, and the kernel scheduler in the operating system, as described for instance by Ingo Lütkebohle: https://roscon.ros.org/2017/presentations/ROSCon%202017%20Determinism%20in%20ROS.pdf

Unfortunately, we didn't measure the actual synchronization error. But I guess you might be able to do that yourself, if you manually annotate a number of events for alle sensors in the rosbags that we have provided.

**Comment by poornimajd** [comment]
Thanks for the quick and detailed reply.
